# Generated by Django 3.2 on 2024-12-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
