name: Django CI

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ "containerization_and_kubernetes" ]
  pull_request:
    branches: [ "containerization_and_kubernetes" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.18
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        poetry-version: '1.8.0'
    - name: Run Tests
      run: |
        python run manage.py test
